/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package unnamedlibrary;
import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.*;
import java.awt.event.*;
import java.io.File;
import java.util.Scanner;
import javax.swing.*;

/**
 *
 * @author FuadAbdullah
 */
public class unnamedMainMenu extends javax.swing.JFrame {
    
    // <editor-fold defaultstate="collapsed" desc="Main Menu Private Variables">
    // Description for private variables
    // -------------------------------------
    // saveDir stores working directory
    // username stores the currently logged in librarian username
    // lID stores the currently looged in librarian ID
    // -------------------------------------
    private String saveDir, username, lID;
    // </editor-fold>
    
    // Main menu form
    public unnamedMainMenu() {
        initComponents();
        initGUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panMain = new javax.swing.JPanel();
        panTop = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblWelcome = new javax.swing.JLabel();
        sptTop = new javax.swing.JSeparator();
        btnLogOut = new javax.swing.JButton();
        panCenter = new javax.swing.JPanel();
        panControl = new javax.swing.JPanel();
        panButtons = new javax.swing.JPanel();
        btnBorrow = new javax.swing.JButton();
        btnRenew = new javax.swing.JButton();
        btnReturn = new javax.swing.JButton();
        btnHistory = new javax.swing.JButton();
        btnManageClient = new javax.swing.JButton();
        btnManageBook = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Menu - unnamed Library Management System");
        setMaximumSize(new java.awt.Dimension(804, 550));
        setMinimumSize(new java.awt.Dimension(804, 550));
        setName("mainMenuFrame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(804, 550));
        setResizable(false);

        panMain.setBackground(new java.awt.Color(51, 51, 51));
        panMain.setMaximumSize(new java.awt.Dimension(804, 450));
        panMain.setMinimumSize(new java.awt.Dimension(804, 450));
        panMain.setPreferredSize(new java.awt.Dimension(804, 450));
        panMain.setLayout(new java.awt.BorderLayout());

        panTop.setBackground(new java.awt.Color(43, 44, 45));
        panTop.setMaximumSize(new java.awt.Dimension(804, 116));
        panTop.setMinimumSize(new java.awt.Dimension(804, 116));

        lblTitle.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("unnamed Library Management System");

        lblWelcome.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        lblWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcome.setText("Logged in as Librarian <Librarian ID>, hello <username>!");

        btnLogOut.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        btnLogOut.setText("Log Out");
        btnLogOut.setToolTipText("Logs out current user");
        btnLogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panTopLayout = new javax.swing.GroupLayout(panTop);
        panTop.setLayout(panTopLayout);
        panTopLayout.setHorizontalGroup(
            panTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panTopLayout.createSequentialGroup()
                .addGroup(panTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sptTop)
                    .addGroup(panTopLayout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(lblTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(lblWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panTopLayout.setVerticalGroup(
            panTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panTopLayout.createSequentialGroup()
                .addGroup(panTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panTopLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lblTitle))
                    .addGroup(panTopLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnLogOut)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sptTop, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblWelcome)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        panMain.add(panTop, java.awt.BorderLayout.PAGE_START);

        panCenter.setBackground(new java.awt.Color(34, 34, 34));
        panCenter.setMaximumSize(new java.awt.Dimension(800, 284));
        panCenter.setMinimumSize(new java.awt.Dimension(800, 284));
        panCenter.setPreferredSize(new java.awt.Dimension(800, 284));

        panControl.setBackground(new java.awt.Color(48, 48, 48));
        panControl.setMaximumSize(new java.awt.Dimension(800, 426));
        panControl.setMinimumSize(new java.awt.Dimension(800, 426));
        panControl.setPreferredSize(new java.awt.Dimension(800, 426));

        panButtons.setMaximumSize(new java.awt.Dimension(788, 414));
        panButtons.setMinimumSize(new java.awt.Dimension(788, 414));
        panButtons.setLayout(new java.awt.GridLayout(2, 3));

        btnBorrow.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 18)); // NOI18N
        btnBorrow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/book1.png"))); // NOI18N
        btnBorrow.setText("   Borrow");
        btnBorrow.setToolTipText("Opens borrowing form");
        btnBorrow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBorrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrowActionPerformed(evt);
            }
        });
        panButtons.add(btnBorrow);

        btnRenew.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 18)); // NOI18N
        btnRenew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/arrow1.png"))); // NOI18N
        btnRenew.setText("   Renew");
        btnRenew.setToolTipText("Opens borrow renew form");
        btnRenew.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRenew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRenewActionPerformed(evt);
            }
        });
        panButtons.add(btnRenew);

        btnReturn.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 18)); // NOI18N
        btnReturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/checked1.png"))); // NOI18N
        btnReturn.setText("   Return");
        btnReturn.setToolTipText("Opens borrow return form");
        btnReturn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });
        panButtons.add(btnReturn);

        btnHistory.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 18)); // NOI18N
        btnHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/history1.png"))); // NOI18N
        btnHistory.setText("   History");
        btnHistory.setToolTipText("Opens borrowing history page");
        btnHistory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoryActionPerformed(evt);
            }
        });
        panButtons.add(btnHistory);

        btnManageClient.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 18)); // NOI18N
        btnManageClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/user1.png"))); // NOI18N
        btnManageClient.setText("    Manage Client");
        btnManageClient.setToolTipText("Opens client management page.");
        btnManageClient.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnManageClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageClientActionPerformed(evt);
            }
        });
        panButtons.add(btnManageClient);

        btnManageBook.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 18)); // NOI18N
        btnManageBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/books1.png"))); // NOI18N
        btnManageBook.setText("   Manage Book");
        btnManageBook.setToolTipText("Opens book management page.");
        btnManageBook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnManageBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageBookActionPerformed(evt);
            }
        });
        panButtons.add(btnManageBook);

        javax.swing.GroupLayout panControlLayout = new javax.swing.GroupLayout(panControl);
        panControl.setLayout(panControlLayout);
        panControlLayout.setHorizontalGroup(
            panControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panControlLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(panButtons, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        panControlLayout.setVerticalGroup(
            panControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panControlLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(panButtons, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panCenterLayout = new javax.swing.GroupLayout(panCenter);
        panCenter.setLayout(panCenterLayout);
        panCenterLayout.setHorizontalGroup(
            panCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panControl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 804, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panCenterLayout.setVerticalGroup(
            panCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCenterLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(panControl, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        panMain.add(panCenter, java.awt.BorderLayout.CENTER);

        getContentPane().add(panMain, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // <editor-fold defaultstate="collapsed" desc="Buttons">
    // This method terminates the current librarian session via log out button
    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(null, "Are you sure you want to log out?", "Logging out!", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (result == JOptionPane.YES_OPTION) {
            cacheClear();
            new unnamedLoginMenu().setVisible(true);
            this.dispose();
        } else {
            // Do nothing
        }
    }//GEN-LAST:event_btnLogOutActionPerformed

    // This method closes main menu and opens borrowing form
    private void btnBorrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrowActionPerformed
        // TODO add your handling code here:
        new unnamedBorrowMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBorrowActionPerformed

    // This method opens the renew page via renew button
    private void btnRenewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRenewActionPerformed
        // TODO add your handling code here:
        new unnamedRenewMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRenewActionPerformed

    // This method opens the return borrowing page via return button
    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        // TODO add your handling code here:
        new unnamedReturnMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnReturnActionPerformed

    // This method opens the borrowing history page via history button
    private void btnHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoryActionPerformed
        // TODO add your handling code here:
        new unnamedHistoryMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHistoryActionPerformed

    // This method opens the book management page via manage book button
    private void btnManageBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageBookActionPerformed
        // TODO add your handling code here:
        new unnamedBookMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnManageBookActionPerformed

    // This method opens the client management page via manage client button
    private void btnManageClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageClientActionPerformed
        // TODO add your handling code here:
        new unnamedClientMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnManageClientActionPerformed
    // </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="Methods">
    // This method will change the welcome text to display currently logged in user information
    private void welcomeText(){
        if (lID != null && username != null) {
            lblWelcome.setText("Logged in as Librarian " + lID + ", hello " + username + "!");
        } else {
            lblWelcome.setForeground(Color.red);
            lblWelcome.setText("UNAUTHORIZED LOGIN! RE-LOGIN TO CONTINUE USING THE SYSTEM!");
        }
    }
    
    // This method will get the information from cache.txt for currently logged in user
    private void getCache(){
        try {
            // To get directory  
            saveDir = System.getProperty("user.dir") + "\\src\\localdb\\";
            // To rename original book.txt to book.bak
            File cache = new File(saveDir + "cache.txt");
            // To check if clientBak.txt is present or not
            if (!cache.exists()){
                throw new Exception("Illegal session!"); // Illegal session as no cache file can be found. one is created upon login
            }
            // This is to instantiate the file opened earlier
            Scanner inputFile = new Scanner(cache);
            // This array is to contain all lines
            String[] matchedID;
            // This is only for debugging!
            // boolean itWorked = false;
            // Read lines from the file until no more are left.
            while (inputFile.hasNext())
            {
                // This is for debugging only!
                // JOptionPane.showMessageDialog(null, "In loop");
                // Read the next line.
                String lEntry = inputFile.nextLine();
                // Split the line by using the delimiter ":" (semicolon) and store into array.
                matchedID = lEntry.split(":");
                lID = matchedID[0];
                username = matchedID[1];
            }
            // Close the clientBak.txt reader
            inputFile.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);

        }
    }
    
    // This method is to delete the session cache upon logout
    private void cacheClear(){
        try {
            // To get directory  
            saveDir = System.getProperty("user.dir") + "\\src\\localdb\\";
            File cache = new File(saveDir + "cache.txt");
            if (cache.exists()) {
                cache.delete();
            }
        } catch (Exception ex) {
            
        }
    }
    
    // This is form load method
    private void initGUI(){
        
        getCache();
        welcomeText();
        // This anon class handles window closing event
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e){
                int selection = JOptionPane.showConfirmDialog(null, "Are you sure you want to exit?", "Closing Window", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (selection == JOptionPane.YES_OPTION) {
                    cacheClear();
                    setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                } else {
                    setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
                }
            }
        });
    }
    // </editor-fold>
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatDarkLaf());
        } catch (Exception ex) {
            System.err.println("Failed to initialize FlatDarkLaf");
        }
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new unnamedMainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrow;
    private javax.swing.JButton btnHistory;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnManageBook;
    private javax.swing.JButton btnManageClient;
    private javax.swing.JButton btnRenew;
    private javax.swing.JButton btnReturn;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JPanel panButtons;
    private javax.swing.JPanel panCenter;
    private javax.swing.JPanel panControl;
    private javax.swing.JPanel panMain;
    private javax.swing.JPanel panTop;
    private javax.swing.JSeparator sptTop;
    // End of variables declaration//GEN-END:variables
}
